# Local Development Override
# Automatically loaded by Docker Compose in addition to compose.yaml
# Includes: dev build target, hot-reload, Adminer, local ports

services:
  # Flask App - Development Configuration
  app:
    build:
      dockerfile: Dockerfile
      target: test  # Development build target with debug enabled
      tags:
        - "fr0gger03/parser-frontend"
    ports:
      - "80:5001"  # Expose on port 80 for local development
    volumes:
      - ./parser:/app/parser  # Mount source for hot reload
    develop:
      watch:
        # Hot reload on code changes
        - action: sync+restart
          path: ./parser
          target: /app/parser
        # Sync static files without restart
        - action: sync
          path: ./parser/static
          target: /app/parser/static
        - action: sync
          path: ./parser/templates
          target: /app/parser/templates
        # Rebuild on dependency changes
        - action: rebuild
          path: ./pyproject.toml
        - action: rebuild
          path: ./uv.lock

  # Database - Development Configuration
  db:
    ports:
      - "5432:5432"  # Expose database port for local access
    volumes:
      - db-data:/var/lib/postgresql/data  # Local named volume

  # Adminer - Database Management UI (dev only)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db-data:

