
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      tags:
        - "thomastwyman557/parser"
    ports:
      - 80:5001
    environment:
      - FLASK_RUN_PORT=5001
      - SECRET_KEY=your-secret-key
      - DATABASE_URL=postgresql://inventorydbuser:password@db:5432/inventorydb
      - UPLOAD_FOLDER=parser/input/
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    volumes:
      - ./parser/sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "inventorydbuser", "-d", "inventorydb"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080

volumes:
  db-data:

