# Production Environment Overrides
# Use with: docker compose -f compose.yaml -f compose.production.yaml up
# Includes: Gunicorn, resource limits, production networking, persistent volumes
# References:
# - https://docs.docker.com/compose/production/
# - https://flask.palletsprojects.com/en/stable/deploying/gunicorn/

services:
  # Flask App - Production Configuration
  app:
    build:
      dockerfile: Dockerfile.production  # Production Dockerfile with Gunicorn
    container_name: workload_parser_app_prod
    ports:
      - "8000:8000"  # Gunicorn port
    volumes:
      # Persistent storage for uploaded files and logs
      - app_input_prod:/app/parser/input
      - app_logs_prod:/app/logs
    networks:
      - app_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Resource limits for production stability
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Database - Production Configuration
  db:
    ports:
      - "5432:5432"  # Expose for external connections if needed
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data  # Production persistent volume
    networks:
      - app_network_prod

volumes:
  # Persistent data volumes
  postgres_data_prod:
    driver: local
  app_input_prod:
    driver: local
  app_logs_prod:
    driver: local

networks:
  app_network_prod:
    driver: bridge

